'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

// 지원 언어 타입
export type SupportedLanguage = 'ko' | 'en' | 'ja' | 'zh' | 'es';

// 언어 설정 인터페이스 (ttsLang 필드 추가)
export interface LanguageConfig {
  code: SupportedLanguage;
  name: string;
  flag: string;
  nativeName: string;
  dir: 'ltr' | 'rtl';
  fontFamily?: string;
  ttsLang: string; // TTS용 언어 코드 추가
}

// 지원 언어 목록 (ttsLang 추가)
export const SUPPORTED_LANGUAGES: LanguageConfig[] = [
  { 
    code: 'ko', 
    name: '한국어', 
    flag: '🇰🇷', 
    nativeName: '한국어',
    dir: 'ltr',
    fontFamily: 'var(--font-noto-sans-kr)',
    ttsLang: 'ko-KR'
  },
  { 
    code: 'en', 
    name: 'English', 
    flag: '🇺🇸', 
    nativeName: 'English',
    dir: 'ltr',
    fontFamily: 'var(--font-inter)',
    ttsLang: 'en-US'
  },
  { 
    code: 'ja', 
    name: '日本語', 
    flag: '🇯🇵', 
    nativeName: '日本語',
    dir: 'ltr',
    fontFamily: 'var(--font-noto-sans-jp)',
    ttsLang: 'ja-JP'
  },
  { 
    code: 'zh', 
    name: '中文', 
    flag: '🇨🇳', 
    nativeName: '中文',
    dir: 'ltr',
    fontFamily: 'var(--font-noto-sans-sc)',
    ttsLang: 'zh-CN'
  },
  { 
    code: 'es', 
    name: 'Español', 
    flag: '🇪🇸', 
    nativeName: 'Español',
    dir: 'ltr',
    fontFamily: 'var(--font-inter)',
    ttsLang: 'es-ES'
  },
];

// 완전한 번역 데이터 타입
interface Translations {
  header: {
    title: string;
    language: string;
    login: string;
    logout: string;
    history: string;
    profile: string;
    settings: string;
    currentSelectedLanguage: string;
  };
  navigation: {
    home: string;
    guides: string;
    favorites: string;
    about: string;
    contact: string;
  };
  home: {
    brandTitle: string;
    title: string;
    subtitle: string;
    subtitle2: string;
    searchPlaceholder: string;
    searchButton: string;
    popularDestinations: string;
    description: string;
    searchPlaceholders?: string[];
    defaultSuggestions?: Array<{ name: string; location: string }>;
    stepTitles: {
      inputLocation: string;
      aiGenerate: string;
      audioPlay: string;
    };
    stepDescriptions: {
      inputLocation: string;
      aiGenerate: string;
      audioPlay: string;
    };
    regionTitles: {
      popularCountries: string;
      europe: string;
      asia: string;
      americas: string;
    };
    regionDescription: string;
    countryAttraction: string;
    startGuide: string;
    destinations: string;
    scrollHint: string;
    popularBadge: string;
    features: {
      personalized: string;
      realTime: string;
      multiLanguage: string;
      offline: string;
      storyteller: string;
      docent: string;
      personalGuide: string;
      audioCommentary: string;
      tourDocent: string;
      selfTour: string;
    };
    countries: {
      [countryId: string]: {
        name: string;
        attractions: string[];
        description: string;
      };
    };
  };
  guide: {
    loading: string;
    error: string;
    chapters: string;
    duration: string;
    difficulty: string;
    nextChapter: string;
    previousChapter: string;
    playAudio: string;
    pauseAudio: string;
    mapView: string;
    listView: string;
    essentialInfo: string;
    locationAccess: string;
    keyFeatures: string;
    historicalContext: string;
    mustSeeHighlights: string;
    safetyGuidelines: string;
    realTimeGuideTitle: string;
    overview: string;
    mustSeePoints: string;
    precautions: string;
    viewingOrder: string;
    audioGuide: string;
    thisPlace: string;
    tourStart: string;
    guideTitle: string;
    loadingGuide: string;
    fetchingGuideData: string;
    currentChapter: string;
    nextMoveGuide: string;
    autoGeneratedIntro: string;
    intro: string;
    aiCustomAudioGuide: string;
  };
  search: {
    placeholder: string;
    searching: string;
    noResults: string;
    tryAgain: string;
    suggestions: string;
    recentSearches: string;
    pressEnterToSearch: string;
  };
  errors: {
    networkError: string;
    serverError: string;
    notFound: string;
    unauthorized: string;
    forbidden: string;
    generalError: string;
  };
  common: {
    loading: string;
    error: string;
    success: string;
    warning: string;
    info: string;
    cancel: string;
    confirm: string;
    save: string;
    delete: string;
    edit: string;
    close: string;
    hide: string;
    exists: string;
    notExists: string;
  };
  history: {
    noResults: string;
    noHistory: string;
    view: string;
    delete: string;
    today: string;
    yesterday: string;
    invalidDate: string;
    preview: string;
    loadFailed: string;
    deleteFailed: string;
    searchInHistory: string;
    searchPlaces: string;
    totalGuides: string;
    daysAgo: string;
    weeksAgo: string;
  };
  date: {
    today: string;
    yesterday: string;
    tomorrow: string;
    thisWeek: string;
    lastWeek: string;
    thisMonth: string;
    lastMonth: string;
  };
  profile: {
    name: string;
    email: string;
    preferences: string;
    language: string;
    notifications: string;
    privacy: string;
    account: string;
    logout: string;
    mypage: string;
  };
  mypage: {
    title: string;
    overview: string;
    guides: string;
    settings: string;
    recentGuides: string;
    favoriteGuides: string;
    totalGuides: string;
    completedTours: string;
    savedLocations: string;
  };
  auth: {
    login: string;
    register: string;
    email: string;
    password: string;
    confirmPassword: string;
    forgotPassword: string;
    rememberMe: string;
    loginWithGoogle: string;
    loginWithFacebook: string;
    createAccount: string;
    alreadyHaveAccount: string;
    noAccount: string;
    signin: string;
    signout: string;
  };
  buttons: {
    submit: string;
    continue: string;
    goBack: string;
    tryAgain: string;
    viewDetails: string;
  };
  languages: {
    ko: string;
    en: string;
    ja: string;
    zh: string;
    es: string;
  };
  audio: {
    chapter: string;
  };
  footer: {
    companyName: string;
    companyDescription: string;
    copyright: string;
    legalInfo: string;
    privacyPolicy: string;
    termsOfService: string;
    aboutUs: string;
    contact: string;
    support: string;
    telegramChannel: string;
    supportHours: string;
    adsenseNotice: string;
    adsensePolicy: string;
  };
  legal: {
    terms: {
      title: string;
      description: string;
      content: string;
      lastUpdated: string;
    };
    privacy: {
      title: string;
      description: string;
      content: string;
      lastUpdated: string;
    };
  };
}

// 기본 번역 데이터 (한국어)
const DEFAULT_TRANSLATIONS: Translations = {
  header: {
    title: 'AI 가이드',
    language: '언어',
    login: '로그인',
    logout: '로그아웃',
    history: '히스토리',
    profile: '프로필',
    settings: '설정',
    currentSelectedLanguage: '현재 선택된 언어'
  },
  navigation: {
    home: '홈',
    guides: '가이드',
    favorites: '즐겨찾기',
    about: '소개',
    contact: '연락처'
  },
  home: {
    brandTitle: 'AI 여행 가이드',
    title: 'AI와 함께하는 스마트 여행',
    subtitle: '개인 맞춤형 가이드로 새로운 여행을 경험하세요',
    subtitle2: '어디든 검색하고 즉시 전문 가이드를 만나보세요',
    searchPlaceholder: '여행지를 검색하세요...',
    searchButton: '검색',
    popularDestinations: '인기 여행지',
    description: 'AI 기술로 생성되는 개인화된 여행 가이드',
    searchPlaceholders: [
      '에펠탑',
      '타지마할',
      '마추픽추',
      '콜로세움',
      '자유의 여신상'
    ],
    defaultSuggestions: [
      { name: '경복궁', location: '서울 종로구' },
      { name: '부산 해운대', location: '부산 해운대구' },
      { name: '제주도 성산일출봉', location: '제주 서귀포시' }
    ],
    stepTitles: {
      inputLocation: '장소 입력',
      aiGenerate: 'AI 생성',
      audioPlay: '오디오 재생'
    },
    stepDescriptions: {
      inputLocation: '궁금한 곳의 이름을 입력하세요',
      aiGenerate: 'AI가 맞춤형 가이드를 생성합니다',
      audioPlay: '생성된 가이드를 음성으로 들어보세요'
    },
    regionTitles: {
      popularCountries: '인기 여행 국가',
      europe: '유럽',
      asia: '아시아',
      americas: '아메리카'
    },
    regionDescription: '다양한 지역의 인기 여행지를 둘러보세요',
    countryAttraction: 'TOP ATTRACTIONS',
    startGuide: 'Start Guide',
    destinations: 'destinations',
    scrollHint: '좌우로 스크롤하여 더 많은 국가를 확인하세요',
    popularBadge: 'POPULAR',
    features: {
      personalized: '맞춤형추천',
      realTime: '실시간가이드',
      multiLanguage: '다국어지원',
      offline: '오프라인사용',
      storyteller: '스토리텔러',
      docent: '도슨트',
      personalGuide: '개인가이드',
      audioCommentary: '오디오해설',
      tourDocent: '투어도슨트',
      selfTour: '셀프투어'
    },
    countries: {
      france: {
        name: '프랑스',
        attractions: ['에펠탑', '루브르 박물관', '베르사유 궁전'],
        description: '로맨틱한 파리와 화려한 문화유산'
      },
      italy: {
        name: '이탈리아',
        attractions: ['콜로세움', '피사의 사탑', '바티칸'],
        description: '고대 로마의 영광과 르네상스 예술'
      },
      spain: {
        name: '스페인',
        attractions: ['사그라다 파밀리아', '알함브라 궁전', '구엘 공원'],
        description: '가우디의 건축과 플라멩코의 열정'
      },
      uk: {
        name: '영국',
        attractions: ['빅벤', '타워 브리지', '버킹엄 궁전'],
        description: '전통과 현대가 조화로운 대영제국'
      },
      germany: {
        name: '독일',
        attractions: ['브란덴부르크 문', '노이슈반슈타인성', '쾰른 대성당'],
        description: '동화 속 성과 깊은 역사의 나라'
      },
      japan: {
        name: '일본',
        attractions: ['후지산', '기요미즈데라', '센소지'],
        description: '전통과 첨단이 공존하는 신비로운 나라'
      },
      china: {
        name: '중국',
        attractions: ['만리장성', '자금성', '천안문 광장'],
        description: '5천년 역사를 간직한 거대한 문명'
      },
      india: {
        name: '인도',
        attractions: ['타지마할', '붉은 요새', '갠지스 강'],
        description: '신비로운 영성과 화려한 궁전들'
      },
      thailand: {
        name: '태국',
        attractions: ['왓 아룬', '대왕궁', '왓 포'],
        description: '황금빛 사원과 미소의 나라'
      },
      singapore: {
        name: '싱가포르',
        attractions: ['마리나 베이 샌즈', '가든스 바이 더 베이', '머라이언'],
        description: '미래도시와 다양한 문화의 만남'
      },
      usa: {
        name: '미국',
        attractions: ['자유의 여신상', '그랜드 캐니언', '타임스퀘어'],
        description: '자유와 꿈의 땅, 무한한 가능성'
      },
      canada: {
        name: '캐나다',
        attractions: ['나이아가라 폭포', 'CN 타워', '밴프 국립공원'],
        description: '광활한 자연과 깨끗한 도시'
      },
      brazil: {
        name: '브라질',
        attractions: ['리우 예수상', '이과수 폭포', '마라카낭 스타디움'],
        description: '삼바와 축구, 열정적인 남미'
      },
      peru: {
        name: '페루',
        attractions: ['마추픽추', '쿠스코', '나스카 라인'],
        description: '잉카 문명의 신비로운 유적들'
      },
      mexico: {
        name: '멕시코',
        attractions: ['치첸이트사', '테오티우아칸', '칸쿤'],
        description: '마야 문명과 카리브해의 낙원'
      }
    }
  },
  guide: {
    loading: '가이드 로딩 중...',
    error: '가이드를 불러올 수 없습니다',
    chapters: '챕터',
    duration: '소요시간',
    difficulty: '난이도',
    nextChapter: '다음 챕터',
    previousChapter: '이전 챕터',
    playAudio: '오디오 재생',
    pauseAudio: '오디오 일시정지',
    mapView: '지도 보기',
    listView: '목록 보기',
    essentialInfo: '필수 정보',
    locationAccess: '위치 및 접근',
    keyFeatures: '주요 특징',
    historicalContext: '역사적 배경',
    mustSeeHighlights: '필수 관람 포인트',
    safetyGuidelines: '안전 수칙',
    realTimeGuideTitle: '실시간 가이드',
    overview: '개요',
    mustSeePoints: '필수관람포인트',
    precautions: '주의사항',
    viewingOrder: '관람순서',
    audioGuide: '오디오 가이드',
    thisPlace: '이곳',
    tourStart: '투어 시작',
    guideTitle: '가이드',
    loadingGuide: '가이드 로딩 중',
    fetchingGuideData: '가이드 데이터를 가져오는 중',
    currentChapter: '현재 챕터',
    nextMoveGuide: '다음 이동 안내',
    autoGeneratedIntro: '자동 생성된 인트로',
    intro: '인트로',
    aiCustomAudioGuide: 'AI 맞춤형 오디오 가이드'
  },
  search: {
    placeholder: '검색어를 입력하세요',
    searching: '검색 중...',
    noResults: '검색 결과가 없습니다',
    tryAgain: '다시 시도',
    suggestions: '추천 검색어',
    recentSearches: '최근 검색',
    pressEnterToSearch: 'Enter키를 눌러 검색하세요'
  },
  errors: {
    networkError: '네트워크 오류가 발생했습니다',
    serverError: '서버 오류가 발생했습니다',
    notFound: '페이지를 찾을 수 없습니다',
    unauthorized: '인증이 필요합니다',
    forbidden: '접근 권한이 없습니다',
    generalError: '오류가 발생했습니다'
  },
  common: {
    loading: '로딩 중...',
    error: '오류',
    success: '성공',
    warning: '경고',
    info: '정보',
    cancel: '취소',
    confirm: '확인',
    save: '저장',
    delete: '삭제',
    edit: '편집',
    close: '닫기',
    hide: '숨기기',
    exists: '있음',
    notExists: '없음'
  },
  history: {
    noResults: '검색 결과가 없습니다',
    noHistory: '검색 기록이 없습니다',
    view: '가이드 보기',
    delete: '삭제',
    today: '오늘',
    yesterday: '어제',
    invalidDate: '잘못된 날짜',
    preview: '가이드 미리보기',
    loadFailed: '히스토리 로드 실패',
    deleteFailed: '히스토리 삭제 실패',
    searchInHistory: '검색 기록에서 찾기',
    searchPlaces: '장소를 검색해보세요',
    totalGuides: '총 {count}개의 가이드',
    daysAgo: '{days}일 전',
    weeksAgo: '{weeks}주 전'
  },
  date: {
    today: '오늘',
    yesterday: '어제',
    tomorrow: '내일',
    thisWeek: '이번 주',
    lastWeek: '지난 주',
    thisMonth: '이번 달',
    lastMonth: '지난 달'
  },
  profile: {
    name: '이름',
    email: '이메일',
    preferences: '설정',
    language: '언어',
    notifications: '알림',
    privacy: '개인정보',
    account: '계정',
    logout: '로그아웃',
    mypage: '마이페이지'
  },
  mypage: {
    title: '마이페이지',
    overview: '개요',
    guides: '가이드',
    settings: '설정',
    recentGuides: '최근 가이드',
    favoriteGuides: '즐겨찾기 가이드',
    totalGuides: '전체 가이드',
    completedTours: '완료된 투어',
    savedLocations: '저장된 장소'
  },
  auth: {
    login: '로그인',
    register: '회원가입',
    email: '이메일',
    password: '비밀번호',
    confirmPassword: '비밀번호 확인',
    forgotPassword: '비밀번호 찾기',
    rememberMe: '로그인 상태 유지',
    loginWithGoogle: 'Google로 로그인',
    loginWithFacebook: 'Facebook으로 로그인',
    createAccount: '계정 만들기',
    alreadyHaveAccount: '이미 계정이 있으신가요?',
    noAccount: '계정이 없으신가요?',
    signin: '로그인',
    signout: '로그아웃'
  },
  buttons: {
    submit: '제출',
    continue: '계속',
    goBack: '돌아가기',
    tryAgain: '다시 시도',
    viewDetails: '자세히 보기'
  },
  languages: {
    ko: '한국어',
    en: 'English',
    ja: '日本語',
    zh: '中文',
    es: 'Español'
  },
  audio: {
    chapter: '챕터'
  },
  footer: {
    companyName: 'GUIDE AI',
    companyDescription: 'AI 기반 개인화 여행 가이드 서비스',
    copyright: '© 2024 GUIDE AI. All rights reserved.',
    legalInfo: '법적 정보',
    privacyPolicy: '개인정보 처리방침',
    termsOfService: '이용약관',
    aboutUs: '회사소개',
    contact: '문의하기',
    support: '고객지원',
    telegramChannel: '텔레그램 채널',
    supportHours: '지원시간: 평일 9시-18시',
    adsenseNotice: '광고 수익 공지',
    adsensePolicy: 'AdSense 정책'
  },
  legal: {
    terms: {
      title: '이용약관',
      description: 'GUIDE AI 서비스 이용약관',
      content: '서비스 이용에 관한 약관 내용',
      lastUpdated: '최종 업데이트'
    },
    privacy: {
      title: '개인정보 처리방침',
      description: 'GUIDE AI 개인정보 처리방침',
      content: '개인정보 처리에 관한 방침 내용',
      lastUpdated: '최종 업데이트'
    }
  }
};

// Context 타입
interface LanguageContextType {
  currentLanguage: SupportedLanguage;
  currentConfig: LanguageConfig;
  setLanguage: (language: SupportedLanguage) => void;
  t: (key: string) => string | string[];
  translations: Translations;
  isLoading: boolean;
  isRTL: boolean;
  detectBrowserLanguage: () => SupportedLanguage;
}

// Context 생성
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 브라우저 언어 감지 함수
const detectBrowserLanguage = (): SupportedLanguage => {
  if (typeof window === 'undefined') return 'ko';
  
  const browserLang = navigator.language.toLowerCase();
  const langCode = browserLang.split('-')[0];
  
  const supportedCodes = SUPPORTED_LANGUAGES.map(lang => lang?.code).filter(Boolean);
  return supportedCodes.includes(langCode as SupportedLanguage) 
    ? langCode as SupportedLanguage 
    : 'ko';
};

// 번역 데이터 로드 함수
async function loadTranslations(language: SupportedLanguage): Promise<Translations> {
  try {
    const cacheKey = `translations-${language}`;
    
    // 세션 스토리지에서 캐시 확인
    if (typeof window !== 'undefined') {
      const cached = sessionStorage.getItem(cacheKey);
      if (cached) {
        try {
          const parsedCache = JSON.parse(cached);
          console.log(`✅ 캐시에서 ${language} 번역 로드`);
          return parsedCache;
        } catch (parseError) {
          console.warn('캐시 파싱 오류, 새로 로드:', parseError);
        }
      }
    }

    // 통합 번역 파일에서 로드 (파일명: translations.json)
    const response = await fetch('/locales/translations.json', {
      cache: 'force-cache'
    });
    
    if (!response.ok) {
      console.warn('번역 파일 로드 실패, 기본값 사용');
      return DEFAULT_TRANSLATIONS;
    }
    
    const allTranslations = await response.json();
    const translations = allTranslations[language] || allTranslations['ko'];
    
    // 안전성 보장 (모든 새로운 필드들 포함)
    const safeTranslations: Translations = {
      ...DEFAULT_TRANSLATIONS,
      ...translations,
      header: {
        ...DEFAULT_TRANSLATIONS.header,
        ...(translations?.header || {})
      },
      navigation: {
        ...DEFAULT_TRANSLATIONS.navigation,
        ...(translations?.navigation || {})
      },
      home: {
        ...DEFAULT_TRANSLATIONS.home,
        ...(translations?.home || {}),
        stepTitles: {
          ...DEFAULT_TRANSLATIONS.home.stepTitles,
          ...(translations?.home?.stepTitles || {})
        },
        stepDescriptions: {
          ...DEFAULT_TRANSLATIONS.home.stepDescriptions,
          ...(translations?.home?.stepDescriptions || {})
        },
        regionTitles: {
          ...DEFAULT_TRANSLATIONS.home.regionTitles,
          ...(translations?.home?.regionTitles || {})
        },
        features: {
          ...DEFAULT_TRANSLATIONS.home.features,
          ...(translations?.home?.features || {})
        },
        countries: {
          ...DEFAULT_TRANSLATIONS.home.countries,
          ...(translations?.home?.countries || {})
        }
      },
      guide: {
        ...DEFAULT_TRANSLATIONS.guide,
        ...(translations?.guide || {})
      },
      search: {
        ...DEFAULT_TRANSLATIONS.search,
        ...(translations?.search || {})
      },
      errors: {
        ...DEFAULT_TRANSLATIONS.errors,
        ...(translations?.errors || {})
      },
      common: {
        ...DEFAULT_TRANSLATIONS.common,
        ...(translations?.common || {})
      },
      date: {
        ...DEFAULT_TRANSLATIONS.date,
        ...(translations?.date || {})
      },
      profile: {
        ...DEFAULT_TRANSLATIONS.profile,
        ...(translations?.profile || {})
      },
      mypage: {
        ...DEFAULT_TRANSLATIONS.mypage,
        ...(translations?.mypage || {})
      },
      auth: {
        ...DEFAULT_TRANSLATIONS.auth,
        ...(translations?.auth || {})
      },
      buttons: {
        ...DEFAULT_TRANSLATIONS.buttons,
        ...(translations?.buttons || {})
      },
      languages: {
        ...DEFAULT_TRANSLATIONS.languages,
        ...(translations?.languages || {})
      },
      audio: {
        ...DEFAULT_TRANSLATIONS.audio,
        ...(translations?.audio || {})
      },
      history: {
        ...DEFAULT_TRANSLATIONS.history,
        ...(translations?.history || {})
      },
      footer: {
        ...DEFAULT_TRANSLATIONS.footer,
        ...(translations?.footer || {})
      },
      legal: {
        ...DEFAULT_TRANSLATIONS.legal,
        ...(translations?.legal || {}),
        terms: {
          ...DEFAULT_TRANSLATIONS.legal.terms,
          ...(translations?.legal?.terms || {})
        },
        privacy: {
          ...DEFAULT_TRANSLATIONS.legal.privacy,
          ...(translations?.legal?.privacy || {})
        }
      }
    };
    
    // 세션 스토리지에 캐시 저장
    if (typeof window !== 'undefined') {
      try {
        sessionStorage.setItem(cacheKey, JSON.stringify(safeTranslations));
      } catch (storageError) {
        console.warn('세션 스토리지 저장 실패:', storageError);
      }
    }
    
    console.log(`✅ ${language} 번역 파일 로드 완료`);
    return safeTranslations;
    
  } catch (error) {
    console.error(`${language} 번역 로드 오류:`, error);
    return DEFAULT_TRANSLATIONS;
  }
}

// Provider 컴포넌트
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<SupportedLanguage>('ko');
  const [translations, setTranslations] = useState<Translations>(DEFAULT_TRANSLATIONS);
  const [isLoading, setIsLoading] = useState(false);

  // 현재 언어 설정 가져오기 (안전한 접근)
  const currentConfig = SUPPORTED_LANGUAGES.find(lang => lang?.code === currentLanguage) || SUPPORTED_LANGUAGES[0] || {
    code: 'ko',
    name: '한국어',
    flag: '🇰🇷',
    nativeName: '한국어',
    dir: 'ltr',
    fontFamily: 'var(--font-noto-sans-kr)',
    ttsLang: 'ko-KR'
  };
  const isRTL = currentConfig?.dir === 'rtl';

  // 언어 변경 함수
  const setLanguage = async (language: SupportedLanguage) => {
    if (language === currentLanguage) return;
    
    setIsLoading(true);
    try {
      const newTranslations = await loadTranslations(language);
      setTranslations(newTranslations);
      setCurrentLanguage(language);
      
      // 로컬 스토리지에 저장
      if (typeof window !== 'undefined') {
        localStorage.setItem('preferred-language', language);
      }
      
      console.log(`언어 변경됨: ${language}`);
    } catch (error) {
      console.error('언어 변경 오류:', error);
    } finally {
      setIsLoading(false);
    }
  };

  // 초기 언어 설정
  useEffect(() => {
    const initializeLanguage = async () => {
      if (typeof window === 'undefined') return;
      
      // 저장된 언어 확인
      const savedLanguage = localStorage.getItem('preferred-language') as SupportedLanguage;
      
      let initialLanguage: SupportedLanguage;
      if (savedLanguage && SUPPORTED_LANGUAGES.some(lang => lang.code === savedLanguage)) {
        initialLanguage = savedLanguage;
      } else {
        initialLanguage = detectBrowserLanguage();
      }
      
      if (initialLanguage !== currentLanguage) {
        await setLanguage(initialLanguage);
      } else {
        // 초기 번역 로드
        const initialTranslations = await loadTranslations(currentLanguage);
        setTranslations(initialTranslations);
      }
    };

    initializeLanguage();
  }, []);

  // 번역 함수
  const t = (key: string): string | string[] => {
    const keys = key.split('.');
    let value: any = translations;
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        console.warn(`Translation key not found: ${key}`);
        return key; // 키를 그대로 반환
      }
    }
    
    return value; // 원래 값 그대로 반환 (string 또는 array)
  };

  const contextValue: LanguageContextType = {
    currentLanguage,
    currentConfig,
    setLanguage,
    t,
    translations,
    isLoading,
    isRTL,
    detectBrowserLanguage
  };

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}

// Hook
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};